### ISSUE TITLE
Reconstruction error triggered by editor for upload without reconstruction

### ISSUE THREAD

**Issue by ErlerPhilipp** [ErlerPhilipp/Pix2Model#47]
my brother uploaded images, probably with the "convert to pointcloud" option. the pointcloud appears correctly in the editor but i get an error when i click on "reconstruct mesh". no info is given in the error-log. manual reconstruction with meshlab works, so i suspect an interface error.

http://netidee.cg.tuwien.ac.at/?id=e6f3d1ee-5eb2-4492-b8a0-0ba2d98d718f

![image](https://user-images.githubusercontent.com/7949665/153770766-a4a3c42f-f089-421e-b6c5-e15eabbc1106.png)

**Comment by sophie-sudoku** [comment]
did the reconstruction work? As far as i know, the error.log for reconstruction (step2) is not yet implemented. This task is worked ob by @thefloff. @ErlerPhilipp please check, if an error is listed in the info.log file in step2. If not - and if the reconstruction did work - i am will check that out. until than i will assign this task to @thefloff

**Comment by ErlerPhilipp** [comment]
just checked again... there is not even a step2 directory on the server, only input and step1. i guess step2 wasn't started for whatever reason.

**Comment by ErlerPhilipp** [comment]
@sophie-sudoku 
seems to work now. only minor issues remain: 
1. i needed to refresh the page (F5) since the refresh button didn't do anything
2. i got a strange entry in the version dropdown box

![image](https://user-images.githubusercontent.com/7949665/159174277-3381b0d3-50c5-49e5-b335-7915ef014679.png)

**Comment by ErlerPhilipp** [comment]
i tried again (upload and "convert to point cloud" and it apparently broke the whole system.
the dashboard shows this error message:
```
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/app-lp47FrbD/lib/python3.9/site-packages/rq/worker.py", line 1061, in perform_job
    rv = job.perform()
  File "/root/.local/share/virtualenvs/app-lp47FrbD/lib/python3.9/site-packages/rq/job.py", line 821, in perform
    self._result = self._execute()
  File "/root/.local/share/virtualenvs/app-lp47FrbD/lib/python3.9/site-packages/rq/job.py", line 844, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/usr/src/app/images_to_mesh/app/process_order.py", line 33, in inner_func
    res = func(*args, **kwargs)
  File "/usr/src/app/images_to_mesh/app/process_order.py", line 98, in _mesh_reconstruction
    return process_clouds(first_job_result)
  File "/usr/src/app/images_to_mesh/processing_steps/mesh_reconstruction/mesh_reconstruction.py", line 13, in process_clouds
    dataset_path: Path = Path(os.path.join(Path(file).parent.parent.parent.parent, 'step2'))
  File "/usr/lib/python3.9/pathlib.py", line 1072, in __new__
    self = cls._from_parts(args, init=False)
  File "/usr/lib/python3.9/pathlib.py", line 697, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python3.9/pathlib.py", line 681, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
now, the system doesn't generate new jobs after uploads.

**Comment by ErlerPhilipp** [comment]
looks like lvm-root went out of space
